"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-j%xh58$jy6s!jlbc19#a6z+oi3gspmt!sq7j5xpew!9%cr+cdd')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Hosts can be provided as a comma-separated list in the ALLOWED_HOSTS env var
ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'Cadastro',
    'sensores',
    'Estufa',
    'Monitor',
    'Clima',
    'BD_FAZENDA',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# CORS configuration: allow all by default, but can be restricted via env vars
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-user-id',
]
# Optionally provide a comma-separated list of allowed origins in CORS_ALLOWED_ORIGINS
if os.getenv('CORS_ALLOWED_ORIGINS'):
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [o for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o]

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{str(BASE_DIR / 'db.sqlite3')}"
    )
}

# Configuração do administrador do PostgreSQL para provisionar bancos de clientes
POSTGRES_ADMIN = {
    'NAME': 'postgres',
    'USER': 'postgres',
    'PASSWORD': '12345',
    'HOST': 'localhost',
    'PORT': '5432',
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'Cadastro.authentication.UsuarioTokenAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Email Configuration
# Usa SMTP real por padrão. Se precisar voltar ao console, defina EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend.
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@agromonitor.com')

SMTP_PLACEHOLDERS = (
    EMAIL_HOST_USER in ('', 'seu_email@gmail.com') or
    EMAIL_HOST_PASSWORD in ('', 'sua_senha_de_app')
)

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
    if SMTP_PLACEHOLDERS
    else os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
)

# Frontend URL para links de cadastro
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# OpenWeatherMap API key for climate service
# Deve ser definida no arquivo .env do backend.
OPENWEATHER_API_KEY = os.getenv('OPENWEATHER_API_KEY', '')

# Configurações do serviço de clima (atualização periódica)
# Habilitar execução automática do worker (usar 'True' para ativar)
CLIMA_AUTO_UPDATE_ENABLED = os.getenv('CLIMA_AUTO_UPDATE_ENABLED', 'False') == 'True'
# Intervalo padrão em segundos entre atualizações (padrão 1800 = 30 minutos)
CLIMA_UPDATE_INTERVAL_SECONDS = int(os.getenv('CLIMA_UPDATE_INTERVAL_SECONDS', '1800'))
# Se True, recomenda-se usar o comando de worker (processo persistente); caso contrário use cron/systemd
CLIMA_USE_WORKER = os.getenv('CLIMA_USE_WORKER', 'False') == 'True'

# Cache Configuration (para rate limiting)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
