# Generated by Django 6.0.3 on 2026-05-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_fix_recebido_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Leitura de Sensor', 'verbose_name_plural': 'Leituras de Sensores'},
        ),
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='sensores_se_sensor__7b8215_idx',
            old_name='sensores_se_sensor__14c3d3_idx',
        ),
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='sensores_se_disposi_5dee2a_idx',
            old_name='sensores_se_disposi_d7e8f9_idx',
        ),
    ]
