# Generated by Django 6.0.3 on 2026-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0005_dispositivo_tenant_alter_comandoatuador_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandoatuador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regraautomacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
