# Generated by Django 6.0.3 on 2026-05-21 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_csv', models.FileField(upload_to='relatorios/', verbose_name='Relatório CSV')),
                ('data_ultimo_relatorio', models.DateTimeField(verbose_name='Data do último relatório')),
                ('data_relatorio_mais_antigo', models.DateTimeField(verbose_name='Data do relatório mais antigo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='BD_FAZENDA.estufa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('role', models.CharField(choices=[('owner', 'Dono da fazenda'), ('supervisor', 'Supervisor'), ('employee', 'Funcionário')], default='employee', max_length=20, verbose_name='Função')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to='BD_FAZENDA.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioConvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('usuario', models.CharField(max_length=15, unique=True, verbose_name='Nome de usuário')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('owner', 'Dono da fazenda'), ('supervisor', 'Supervisor'), ('employee', 'Funcionário')], max_length=20, verbose_name='Função pretendida')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Token')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('utilizado', models.BooleanField(default=False, verbose_name='Utilizado')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_criados', to='BD_FAZENDA.usuario')),
                ('usuario_criado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convite_origem', to='BD_FAZENDA.usuario')),
            ],
        ),
    ]
