# Generated by Django 6.0.3 on 2026-06-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clima', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='previsaotempo',
            new_name='Clima_previ_localid_bb8be1_idx',
            old_name='Clima_previ_localid_c5a3f4_idx',
        ),
        migrations.RenameIndex(
            model_name='previsaotempo',
            new_name='Clima_previ_data_ho_84f150_idx',
            old_name='Clima_previ_data_ho_c5a3f4_idx',
        ),
    ]
