# Generated by Django 5.2.1 on 2026-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clima', '0002_rename_clima_previ_localid_c5a3f4_idx_clima_previ_localid_bb8be1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidadeclima',
            name='clima_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tag de Clima'),
        ),
    ]
