# Generated by Django 6.0.3 on 2026-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clima', '0003_localidadeclima_clima_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Anotação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='notas_clima', to='Cadastro.usuario')),
            ],
            options={
                'verbose_name': 'Nota do Usuário',
                'verbose_name_plural': 'Notas do Usuário',
                'ordering': ['-criado_em'],
            },
        ),
    ]
