# Generated by Django 6.0.3 on 2026-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_hash', models.CharField(max_length=255, unique=True)),
                ('categoria', models.IntegerField(default=1)),
                ('tentativas_falhas', models.IntegerField(default=0)),
                ('bloqueio', models.BooleanField(default=False)),
            ],
        ),
    ]
