# Generated by Django 6.0.3 on 2026-05-11 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0003_remove_usuario_categoria_usuario_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do cliente')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug do cliente')),
                ('db_name', models.CharField(max_length=150, unique=True, verbose_name='Nome do banco')),
                ('db_user', models.CharField(default='postgres', max_length=100, verbose_name='Usuário do banco')),
                ('db_password', models.CharField(blank=True, max_length=255, verbose_name='Senha do banco')),
                ('db_host', models.CharField(default='localhost', max_length=100, verbose_name='Host do banco')),
                ('db_port', models.CharField(default='5432', max_length=10, verbose_name='Porta do banco')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('provisionado', models.BooleanField(default=False, verbose_name='Provisionado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='Cadastro.usuario')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
    ]
