# Generated by Django 6.0.3 on 2026-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0004_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioconvite',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('owner', 'Owner - Cliente'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='employee', max_length=20, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('owner', 'Owner - Cliente'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='owner', max_length=20, verbose_name='Função'),
        ),
    ]
