# Generated by Django 6.0.3 on 2026-05-11 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0005_usuarioconvite_role_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último login'),
        ),
    ]
