# Generated by Django 5.2.1 on 2026-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0007_recuperacaosenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='mqtt_broker',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Broker MQTT'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mqtt_port',
            field=models.PositiveIntegerField(default=1883, verbose_name='Porta MQTT'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mqtt_topic_prefix',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prefixo de tópicos MQTT'),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuarioconvite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
