# Generated by Django 6.0.3 on 2026-06-01 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0009_alter_recuperacaosenha_id_alter_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='Chave do token')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='Cadastro.usuario')),
            ],
            options={
                'verbose_name': 'Token de Usuário',
                'verbose_name_plural': 'Tokens de Usuários',
            },
        ),
    ]
