# Generated by Django 6.0.3 on 2026-05-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='info', max_length=20, verbose_name='Nível')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de resolução')),
                ('usuario_relacionado', models.IntegerField(blank=True, null=True, verbose_name='ID do usuário relacionado')),
            ],
            options={
                'verbose_name': 'Alerta do Sistema',
                'verbose_name_plural': 'Alertas do Sistema',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(verbose_name='ID do usuário')),
                ('usuario_nome', models.CharField(max_length=150, verbose_name='Nome do usuário')),
                ('usuario_email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('tipo_atividade', models.CharField(max_length=100, verbose_name='Tipo de atividade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
            ],
            options={
                'verbose_name': 'Atividade do Usuário',
                'verbose_name_plural': 'Atividades dos Usuários',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('total_usuarios', models.IntegerField(default=0, verbose_name='Total de usuários')),
                ('total_owners', models.IntegerField(default=0, verbose_name='Total de owners')),
                ('total_supervisores', models.IntegerField(default=0, verbose_name='Total de supervisores')),
                ('total_funcionarios', models.IntegerField(default=0, verbose_name='Total de funcionários')),
                ('total_estufas', models.IntegerField(default=0, verbose_name='Total de estufas')),
                ('total_relatorios', models.IntegerField(default=0, verbose_name='Total de relatórios')),
                ('usuarios_ativos_hoje', models.IntegerField(default=0, verbose_name='Usuários ativos hoje')),
                ('novos_usuarios_hoje', models.IntegerField(default=0, verbose_name='Novos usuários hoje')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Estatística da Plataforma',
                'verbose_name_plural': 'Estatísticas da Plataforma',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MetricasTempoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave da métrica')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('unidade', models.CharField(blank=True, max_length=50, verbose_name='Unidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Métrica em Tempo Real',
                'verbose_name_plural': 'Métricas em Tempo Real',
            },
        ),
    ]
